version: '3.8'
services:
  product-service:
    build: ./product-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/productdb
      - SPRING_DATASOURCE_USERNAME=sabhanda
      - SPRING_DATASOURCE_PASSWORD=sabhanda
    depends_on:
      - db
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=sabhanda
      - SPRING_DATASOURCE_PASSWORD=sabhanda
    depends_on:
      - db
    networks:
      - microservices-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sabhanda
      POSTGRES_PASSWORD: sabhanda
      POSTGRES_DB: productdb  # Default database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql  # Add init script to create the second DB
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    restart: always

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data: